# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8e55cecfc80f440454d655ad95b26fc4d14e881224085ddd99d819781af48b327a2e60bb929b5eb07ade31f07a958749e9bc127068deb5e2fa43843cf77e5c8

test:
  secret_key_base: 11727ddd6ca6646ca378e9f50e9b09ad4c1c3bba3c450fe59edb3948b29dd09f5994503cadb81e59a1de81bc7e4fc68ba3f309b9df4b40982e98143c33126241

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
